$ErrorActionPreference = "Stop"
Write-Host "B.A.L.O.N local CV demo"
Write-Host "Backend:  http://127.0.0.1:8000"
Write-Host "Frontend: http://127.0.0.1:5173"
Write-Host "Worker:   http://127.0.0.1:8765"
Write-Host ""
Write-Host "Start these in separate terminals:"
Write-Host "1. python -m uvicorn backend.main:app --host 127.0.0.1 --port 8000"
Write-Host "2. npm.cmd run dev --workspace frontend"
Write-Host "3. python -m cv_worker.main"
Write-Host ""
Write-Host "Replay fallback:"
Write-Host "python scripts/demo_cv_replay.py --scenario ALL"
